name: Java CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'zulu'
        cache: 'maven'
    - name: Maven Download all dependencies
      run: mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline
    - name: Maven Build
      run: mvn -B package --file pom.xml -Dtest=GistTest,UserTest
